name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKG_NAME: my-react-components

    steps:
      - name: Release setup
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ env.PKG_NAME }}
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@8zca'

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: yarn && yarn build

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
