name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: write
      packages: write 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@8zca'
      - run: |
          yarn && yarn build

      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v2
      #   id: semantic # Need an `id` for output variables
      #   with:
      #     extra_plugins: |
      #       @semantic-release/git
      #       @semantic-release/changelog
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.PKG_TOKEN }}

      # - run: yarn add semantic-release @semantic-release/changelog @semantic-release/git
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
